# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_integracao', models.DateField(verbose_name='Data da Integração')),
                ('apresentador', models.CharField(max_length=200, verbose_name='Apresentador SESMET')),
                ('missao_visao_valores', models.BooleanField(default=False, verbose_name='Missão, Visão e Valores')),
                ('normas_seguranca', models.BooleanField(default=False, verbose_name='Normas de Segurança')),
                ('uso_epis', models.BooleanField(default=False, verbose_name='Uso e Cuidados com EPIs')),
                ('procedimentos_emergencia', models.BooleanField(default=False, verbose_name='Procedimentos de Emergência')),
                ('concluida', models.BooleanField(default=False, verbose_name='Integração Concluída')),
                ('obs', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracao_seguranca', to='admissional.colaborador')),
            ],
            options={
                'verbose_name': 'Integração de Segurança',
                'verbose_name_plural': 'Integrações de Segurança',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da OS')),
                ('descricao_riscos', models.TextField(verbose_name='Descrição dos Riscos')),
                ('medidas_preventivas', models.TextField(verbose_name='Medidas Preventivas')),
                ('epis_obrigatorios', models.TextField(verbose_name='EPIs Obrigatórios')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('assinado', models.BooleanField(default=False, verbose_name='Colaborador Assinou?')),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='admissional.colaborador')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_epi', models.CharField(choices=[('luva', 'Luva'), ('calcado', 'Calçado de Segurança'), ('protetor_auricular', 'Protetor Auricular'), ('respirador_p2', 'Respirador P2'), ('oculos', 'Óculos de Proteção'), ('uniforme', 'Uniforme'), ('capacete', 'Capacete'), ('cinto_seguranca', 'Cinto de Segurança'), ('avental', 'Avental de Proteção')], max_length=30, verbose_name='Tipo de EPI')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('numero_ca', models.CharField(blank=True, max_length=20, verbose_name='Número CA')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade/Substituição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo / Em Uso'), ('vencido', 'Vencido — Substituição Necessária'), ('substituido', 'Substituído'), ('perdido', 'Perdido / Danificado')], default='ativo', max_length=20)),
                ('motivo_substituicao', models.CharField(choices=[('vencimento', 'Vencimento da Validade'), ('dano', 'Dano / Desgaste'), ('perda', 'Perda'), ('troca_cargo', 'Troca de Cargo/Função'), ('inicial', 'Entrega Inicial')], default='inicial', max_length=20, verbose_name='Motivo')),
                ('assinado', models.BooleanField(default=False, verbose_name='Colaborador Assinou?')),
                ('obs', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='admissional.colaborador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epis_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de EPI',
                'verbose_name_plural': 'Registros de EPIs',
                'ordering': ['-data_entrega'],
            },
        ),
    ]
