# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro'), ('gateway', 'Gateway de Processo')], default='info', max_length=20)),
                ('modulo', models.CharField(choices=[('recrutamento', 'Recrutamento'), ('admissional', 'Admissional'), ('administrativo', 'Administrativo'), ('sesmet', 'SESMET'), ('compras', 'Compras'), ('financeiro', 'Financeiro'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('url_acao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('rh', 'RH / Departamento Pessoal'), ('financeiro', 'Financeiro / Fiscal'), ('sesmet', 'SESMET / Segurança do Trabalho'), ('compras', 'Compras / Almoxarifado'), ('operacional', 'Operacional')], default='operacional', max_length=20)),
                ('marca', models.CharField(choices=[('eco_premium', 'Eco Premium'), ('trip_premium', 'Trip Premium'), ('log_premium', 'Log Premium'), ('matriz', 'Matriz Ecopremium')], default='eco_premium', max_length=20)),
                ('unidade', models.CharField(default='Matriz', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('avatar_iniciais', models.CharField(blank=True, max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
