# Generated by Django 6.0.5 on 2026-06-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aprovacaoregistro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aprovacaoregistro',
            new_name='core_aprova_content_355bbd_idx',
            old_name='core_aprova_content_idx',
        ),
        migrations.RenameIndex(
            model_name='aprovacaoregistro',
            new_name='core_aprova_status_678fb9_idx',
            old_name='core_aprova_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aprovacaoregistro',
            new_name='core_aprova_modulo_4caa64_idx',
            old_name='core_aprova_modulo_idx',
        ),
    ]
