# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=200, verbose_name='Nome da Vaga')),
                ('quantidade_colaboradores', models.PositiveIntegerField(verbose_name='Quantidade de Colaboradores')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('perfil_desejado', models.TextField(verbose_name='Perfil Desejado')),
                ('atividades', models.TextField(verbose_name='Atividades da Função')),
                ('horario_trabalho', models.CharField(max_length=100, verbose_name='Horário de Trabalho')),
                ('tipo_contratacao', models.CharField(choices=[('clt', 'CLT'), ('pj', 'Pessoa Jurídica'), ('temporario', 'Temporário'), ('estagio', 'Estágio'), ('autonomo', 'Autônomo')], max_length=20, verbose_name='Tipo de Contratação')),
                ('valor_salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor/Salário')),
                ('previsao_inicio', models.DateField(verbose_name='Previsão de Início')),
                ('exige_experiencia', models.BooleanField(default=False, verbose_name='Exige Experiência?')),
                ('descricao_experiencia', models.TextField(blank=True, verbose_name='Descrição da Experiência Necessária')),
                ('motivo_solicitacao', models.TextField(verbose_name='Motivo da Solicitação')),
                ('gestor_responsavel', models.CharField(max_length=200, verbose_name='Nome do Gestor Responsável')),
                ('status', models.CharField(choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('informacoes_incompletas', 'Informações Incompletas'), ('em_selecao', 'Em Seleção'), ('aguardando_entrevista', 'Aguardando Entrevista Final'), ('preenchida', 'Vaga Preenchida'), ('cancelada', 'Cancelada')], default='aguardando_aprovacao', max_length=30)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gestor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_abertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Gestor')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('etapa_atual', models.CharField(choices=[('triagem', 'Triagem / Seleção'), ('avaliacao_dp', 'Avaliação DP / Comportamental'), ('entrevista_final', 'Entrevista Final com Gestor'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('desistente', 'Desistente')], default='triagem', max_length=20)),
                ('aprovado', models.BooleanField(blank=True, null=True, verbose_name='Aprovado?')),
                ('curriculum_obs', models.TextField(blank=True, verbose_name='Observações do Currículo')),
                ('avaliacao_comportamental', models.TextField(blank=True, verbose_name='Avaliação Comportamental')),
                ('resultado_entrevista', models.TextField(blank=True, verbose_name='Resultado da Entrevista Final')),
                ('encaminhado_admissao', models.BooleanField(default=False, verbose_name='Encaminhado para Admissão?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_avaliados', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='recrutamento.vaga')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
