# Generated by Django 6.0.5 on 2026-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('curriculo_texto', models.TextField(blank=True, verbose_name='Texto Extraído do Currículo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talento',
                'verbose_name_plural': 'Banco de Talentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
    ]
