# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota_fiscal', 'Nota Fiscal'), ('contrato', 'Contrato'), ('reembolso', 'Reembolso'), ('pagamento', 'Pagamento'), ('faturamento', 'Faturamento'), ('recibo', 'Recibo'), ('boleto', 'Boleto Bancário')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('centro_custo', models.CharField(max_length=100, verbose_name='Centro de Custo')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('cnpj_emitente', models.CharField(blank=True, max_length=18, verbose_name='CNPJ do Emitente')),
                ('razao_social_emitente', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('contratos_vinculados', models.CharField(blank=True, max_length=200, verbose_name='Contratos Vinculados')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_auditoria', 'Em Auditoria Interna'), ('informacoes_incorretas', 'Informações Incorretas'), ('aguardando_correcao', 'Aguardando Correção'), ('aprovado_lancamento', 'Aprovado para Lançamento'), ('lancado', 'Lançado no ERP'), ('arquivado', 'Arquivado')], default='recebido', max_length=30)),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Financeiro',
                'verbose_name_plural': 'Documentos Financeiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do Lançamento')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('provisao', 'Provisão'), ('estorno', 'Estorno')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('centro_custo', models.CharField(max_length=100, verbose_name='Centro de Custo')),
                ('competencia', models.DateField(verbose_name='Mês de Competência')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_validacao', 'Em Validação'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado — Corrigir'), ('finalizado', 'Finalizado no ERP')], default='rascunho', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='financeiro.documentofinanceiro', verbose_name='Documento de Origem')),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_efetuados', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento ERP',
                'verbose_name_plural': 'Lançamentos ERP',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('valor_correto', 'Valor Correto'), ('centro_custo_ok', 'Centro de Custo Válido'), ('unidade_ok', 'Unidade Correta'), ('cnpj_valido', 'CNPJ Válido'), ('contrato_vinculado', 'Contrato Vinculado Correto'), ('data_valida', 'Data de Emissão Válida')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Conferido — OK'), ('divergente', 'Divergente')], default='pendente', max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('verificado_em', models.DateTimeField(auto_now=True)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_auditados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='financeiro.documentofinanceiro')),
            ],
            options={
                'verbose_name': 'Item de Auditoria',
                'verbose_name_plural': 'Itens de Auditoria',
                'unique_together': {('documento', 'item')},
            },
        ),
    ]
