# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('marca', models.CharField(choices=[('eco_premium', 'Eco Premium'), ('trip_premium', 'Trip Premium'), ('log_premium', 'Log Premium')], default='eco_premium', max_length=20, verbose_name='Marca')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Em Férias'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], default='ativo', max_length=20)),
                ('pis_pasep', models.CharField(blank=True, max_length=20, verbose_name='PIS/PASEP')),
                ('ctps', models.CharField(blank=True, max_length=30, verbose_name='CTPS')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Admissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_nome', models.CharField(max_length=200, verbose_name='Nome do Candidato')),
                ('candidato_email', models.EmailField(max_length=254, verbose_name='E-mail do Candidato')),
                ('candidato_telefone', models.CharField(blank=True, max_length=20)),
                ('vaga_nome', models.CharField(max_length=200, verbose_name='Vaga')),
                ('unidade_destino', models.CharField(max_length=100, verbose_name='Unidade de Destino')),
                ('status', models.CharField(choices=[('aguardando_documentos', 'Aguardando Documentos'), ('documentos_em_analise', 'Documentos em Análise'), ('documentos_pendentes', 'Documentos Pendentes'), ('cadastro_sistema', 'Cadastro no Sistema'), ('contrato_gerado', 'Contrato Gerado'), ('integracao', 'Em Integração'), ('epis_entregues', 'EPIs Entregues'), ('liberado', 'Liberado para Unidade'), ('concluido', 'Concluído')], default='aguardando_documentos', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissao', to='admissional.colaborador')),
            ],
            options={
                'verbose_name': 'Processo Admissional',
                'verbose_name_plural': 'Processos Admissionais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdmissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('ctps', 'Carteira de Trabalho (CTPS)'), ('pis', 'PIS/PASEP'), ('comprovante_residencia', 'Comprovante de Residência'), ('certidao_nascimento', 'Certidão de Nascimento'), ('certidao_casamento', 'Certidão de Casamento'), ('diploma', 'Diploma/Certificado Escolar'), ('foto_3x4', 'Foto 3x4'), ('atestado_saude', 'Atestado de Saúde Ocupacional (ASO)'), ('dados_bancarios', 'Dados Bancários'), ('antecedentes', 'Certidão de Antecedentes Criminais')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_analise', 'Aguardando Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado — Solicitar Correção')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('admissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='admissional.admissao')),
            ],
            options={
                'verbose_name': 'Documento Admissional',
                'verbose_name_plural': 'Documentos Admissionais',
                'unique_together': {('admissao', 'tipo')},
            },
        ),
    ]
