# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('controle_documental', 'Controle Documental'), ('contratos', 'Contratos'), ('fornecedores', 'Fornecedores'), ('reembolsos', 'Reembolsos'), ('pagamentos', 'Pagamentos'), ('relatorios', 'Relatórios'), ('agendas_reunioes', 'Agendas e Reuniões'), ('apoio_operacional', 'Apoio Operacional')], max_length=30, verbose_name='Tipo de Demanda')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('requisitante', models.CharField(max_length=200, verbose_name='Requisitante')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_triagem', 'Em Triagem'), ('informacoes_incompletas', 'Informações Incompletas'), ('em_execucao', 'Em Execução'), ('aguardando_ajuste', 'Aguardando Ajuste'), ('arquivada', 'Arquivada / Concluída')], default='recebida', max_length=30)),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo de Rejeição/Ajuste')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('requisitante_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Demanda Administrativa',
                'verbose_name_plural': 'Demandas Administrativas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
