# Generated by Django 6.0.5 on 2026-05-31 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Material')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('consumo', 'Material de Consumo'), ('limpeza', 'Material de Limpeza'), ('escritorio', 'Material de Escritório'), ('ferramentas', 'Ferramentas'), ('epi', 'EPI / Segurança'), ('informatica', 'Informática'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], default='consumo', max_length=20)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('pc', 'Pacote'), ('kg', 'Quilograma'), ('lt', 'Litro'), ('mt', 'Metro'), ('pr', 'Par'), ('rl', 'Rolo')], default='un', max_length=5)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd. em Estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Estoque Mínimo')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('fornecedor_preferencial', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor Preferencial')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização no Almoxarifado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('unidade_destino', models.CharField(max_length=100, verbose_name='Unidade de Destino')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise de Estoque'), ('atendido_interno', 'Atendido pelo Estoque'), ('compra_externa', 'Encaminhado para Compra Externa'), ('aguardando_entrega', 'Aguardando Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='compras.material', verbose_name='Material')),
                ('solicitante_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Material',
                'verbose_name_plural': 'Solicitações de Material',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, verbose_name='CNPJ do Fornecedor')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('prazo_entrega', models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('status', models.CharField(choices=[('em_cotacao', 'Em Cotação'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado — Nova Cotação'), ('pedido_emitido', 'Pedido Emitido ao Fornecedor'), ('aguardando_recebimento', 'Aguardando Recebimento'), ('recebido_conferencia', 'Recebido — Em Conferência'), ('entrada_estoque', 'Entrada no Estoque'), ('concluido', 'Concluído')], default='em_cotacao', max_length=30)),
                ('numero_pedido', models.CharField(blank=True, max_length=30, verbose_name='Número do Pedido')),
                ('nota_fiscal', models.CharField(blank=True, max_length=30, verbose_name='Nota Fiscal')),
                ('obs', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compras.solicitacaomaterial', verbose_name='Solicitação de Origem')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-criado_em'],
            },
        ),
    ]
